### ISSUE TITLE
ScrollViewer event?

### ISSUE THREAD

**Issue by arivoir** [SvenEV/Xamzor#1]
I have one question. How would you add a _ScrollChanged_ event to the _ScrollViewer_ control?

**Comment by SvenEV** [comment]
I guess you would need to:
1. Add a handler for the [onscroll event](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onscroll) on the outermost div of the ScrollViewer component (see [Blazor docs: Event Handling](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#event-handling))
2. Define a component parameter "ScrollChanged" of type `Action` or some other delegate
3. Invoke "ScrollChanged" from within the event handler

But please note that Xamzor is only an experimental project which is no longer in active development.

**Comment by arivoir** [comment]
Thanks for the idea. I'm trying to understand Blazor, and this project is helping me. Thanks.

**Comment by arivoir** [comment]
Hi Sven, Do you think there is a way to get scrollTop (VerticalOffset) without using JavaScript interop? Any idea is welcome.

**Comment by SvenEV** [comment]
No, I can't think of a way to do this without JS interop.
